### ISSUE TITLE
Made a basey sass version

### ISSUE THREAD

**Issue by adamk22** [zslabs/basey-theme#10]
I tweaked the basey theme to work with UIkit sass, here is the repo: https://github.com/adamk22/basey-theme-sass 

It still isn't perfect, but can be used as a starter theme for people that prefer UIkit sass. Let me know what you think!

**Comment by zslabs** [comment]
Very cool! I have some plans for the future of Basey Theme brewing and am glad to see you could take this and spin it to better fit your needs!

**Comment by adamk22** [comment]
If you need any help, I'd gladly lend a hand or two!
