### ISSUE TITLE
Nav: Depth 3 support

### ISSUE THREAD

**Issue by rameden** [zslabs/basey-theme#13]
It would be awesome if we could get navigation depth 3 support. Right now when you update the main navigation to depth 3 it breaks the navigation drop down.

![wordpress_3_drop_down_menu_tutorial](https://cloud.githubusercontent.com/assets/1105847/21746487/c5ce3e1a-d514-11e6-8d75-0874cdd94e1d.png)

**Comment by zslabs** [comment]
Hey there - at this time it's not something I'll have time to tackle since I'll be moving Basey Theme in a different direction (more on that soon hopefully). Feel free to open a PR. Thanks!
