### ISSUE TITLE
Wordpress menu structure error

### ISSUE THREAD

**Issue by nathanaelbaaij** [zslabs/basey-theme#14]
I have copied your /inc/menu.php class in my wordpress functions.php, but the Wordpress menu structure isn't the same as menu in the website. When I try to create a dropdown menu with multiple sub-items in wordpress, the wp_nav_menu only shows one dropdown item.

I guess the html code does not look correct either, because the dropmenu li items does not have a ul wrapped around.

![image](https://user-images.githubusercontent.com/7000976/27480108-f7018b42-5816-11e7-990f-8d9bab82b2ea.png)

I hope you can help me out.

I use Wordpress version 4.8 with UIKit 3 Beta.

This is the wp_nav_menu array:

    wp_nav_menu(
        array(
            'theme_location' => 'header-menu',
            'menu' => 4,
            'container' => false,
            'container_class' => 'menu-{menu slug}-container',
            'container_id' => '',
            'menu_class' => '',
            'menu_id' => '',
            'echo' => true,
            'fallback_cb' => 'wp_page_menu',
            'before' => '',
            'after' => '',
            'link_before' => '',
            'link_after' => '',
            'items_wrap' => '<ul class="uk-navbar-nav">%3$s</ul>',
            'depth' => 1,
            'walker' => new basey_primary_menu()
        )
    );

**Comment by zslabs** [comment]
Hi, 
I unfortunately haven't tested this with UIKit 3, but have you taken a look at the [example menu](https://github.com/zslabs/basey-theme/blob/master/inc/output.php#L23)?

**Comment by nathanaelbaaij** [comment]
I haven't seen the example menu yet, thanks!
