### ISSUE TITLE
LESS not finding bower_components

### ISSUE THREAD

**Issue by martinbetz** [zslabs/basey-theme#4]
When running `gulp`, the `styles` task fails with the following error message:

```
Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    'bower_components/uikit/themes/almost-flat/variables.less' wasn't found in file /Applications/MAMP/htdocs/volkerbeck/wp-content/themes/basey-theme/assets/css/src/app.less line no. 10
Details:
    type: File
    filename: /Applications/MAMP/htdocs/wp-content/themes/basey-theme/assets/css/src/app.less
    index: 217
    line: 10
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: // LESS related,@import "bower_components/uikit/themes/almost-flat/variables.less";,
    lineNumber: 10
    fileName: /Applications/MAMP/htdocs/wp-content/themes/basey-theme/assets/css/src/app.less
```

The problem should be about the relative path and from the first quick analysis, this does not surprise me.

`app.less` is in folder `assets > css > src`, `variables.less` is in folder `app > bower_components > uikit > themes > almost_flat`.

The import in `app.less` however is `bower_components...`.

Is this an error? Or do I do something wrong?

**Comment by zslabs** [comment]
https://github.com/zslabs/basey-theme/releases/tag/7.0.0 should resolve this.
