### ISSUE TITLE
Search result counts with multiple search terms

### ISSUE THREAD

**Issue by ericbrissette** [zslabs/basey-theme#5]
When I search using more than one search term, the count of each type of result is broken, so for example the headings for the different types of results will say "0 Post Found" or "0 Page Found" even though posts and pages were returned.  

Same goes for the Filter subnav at the top of the results.

I have been removing the counts and using more generic wording for the filter and headings.

**Comment by zslabs** [comment]
Hey Eric,
Can you see if https://github.com/zslabs/basey-theme/commit/a3d7d6a87ea94fe4ff7e73c96c8240851d3a6931 resolves this? Check out the comments at the top of that commit, as those may have been the combined issues. Thanks!

**Comment by ericbrissette** [comment]
No, I don't believe it does.  I grabbed the latest /search.php and /inc/search.php

If I search for only one term, the counts are correct.  If I search for two terms, doesn't matter what they are, the counts are always zero.

**Comment by zslabs** [comment]
I tested this with a "very generic" use-case:

* Created 3 posts, "Test Post 1", "Test Post 2", and "Test Post 3"
* Searched for "test post"
* Returned those 3 results

Do you have any other search plugins enabled? Definitely want to replicate what you're seeing on your end to get that fixed if you can explain a bit further so I can test on my end. Thanks!
