### ISSUE TITLE
Wordpress Menu Walker

### ISSUE THREAD

**Issue by Samanw** [zslabs/basey-theme#6]
Hi
Could  you please help me with wordpress menu 
trying to create menu walker for uikit
i used your codes but it didnt works
i think it need to be updated

**Comment by zslabs** [comment]
Hi,
Are you sure you're assigning your menu to the "Primary Menu" location? Just tired with WordPress 4.2 and everything is working as expected on my end. Closing this for now. Will have an update out in a few days around UIkit dependencies and will double-check the logic behind this. Thanks.

**Comment by Samanw** [comment]
this is the thing i copy in function.php:
  register_nav_menus(

    array( 'Primary-Menu' => __( 'Primary Menu' ) )

  );
and
https://github.com/zslabs/basey-theme/blob/master/inc/menus.php

--
in my header.php where i put menu

wp_nav_menu( array( 'theme_location' => 'Primary Menu', 'walker' => 'basey_primary_menu' ) );

**Comment by zslabs** [comment]
This is the complete function that is referenced in `/inc/output.php`:

	wp_nav_menu( array(
		'menu'              => 'primary',
		'theme_location'    => 'primary',
		'depth'             => 2,
		'container'         => '',
		'menu_class'        => 'uk-navbar-nav uk-hidden-small',
		'fallback_cb'       => 'basey_primary_menu::fallback',
		'walker'            => new basey_primary_menu())
	);

**Comment by Samanw** [comment]
thx
made it with your helps
gj

**Comment by Samanw** [comment]
Hi Again,
how can i disable mobile menu in walker?

**Comment by zslabs** [comment]
Inside of `/inc/output.php` you'll find a function called `basey_content_after_output()`. That includes a reference to the off-canvas menu. There's also an off-canvas trigger in the header you'll want to take care of.
