### ISSUE TITLE
Update CSS/Less Edits

### ISSUE THREAD

**Issue by JxnGraphix** [zslabs/basey-theme#9]
Please excuse my "noob-ness" as I am attempting to learn workflow automation... Is gulp's watch mode suppose to update edits/changes made in uikit/src/less/core files? How do I get the site to reflect the changes made to the .less files? I tried running gulp scripts, copy and watch tasks but none of them worked. Any help would be appreciated.

**Comment by zslabs** [comment]
Hey,
The `watch` command will not execute any tasks for edits to core UIkit files since as it's a pretty common rule to never edit those src files. If you've updated the core version of UIkit (for example), you can just run a normal `gulp` to run through everything.
